[package]
name = "web_crawler"
version = "0.1.0"
authors = ["tomos <tomos@commerceblock.com>"]
edition = "2018"


[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
rayon = "0.6.0"
regex = "1"

[dev-dependencies]
tokio-test = "*"
